"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isRetryableError = exports.getHttpStatusCode = exports.toAPISuccessResponse = exports.toAPIErrorResponse = exports.serializeError = exports.ChecksumMismatchError = exports.TenantIsolationError = exports.CircularDependencyError = exports.RelationshipError = exports.LifecycleExpiredError = exports.LifecycleTransitionError = exports.SensitivityViolationError = exports.DomainError = exports.PodcastError = exports.TransformationError = exports.VectorOperationError = exports.ChunkingError = exports.ExtractionError = exports.IndexingError = exports.EmbeddingError = exports.ContentProcessingError = exports.InvalidResponseError = exports.QuotaExceededError = exports.ServiceUnavailableError = exports.APIError = exports.NetworkError = exports.TimeoutError = exports.RateLimitError = exports.AIProviderError = exports.ExternalServiceError = exports.SchemaValidationError = exports.OutOfRangeError = exports.InvalidFormatError = exports.MissingRequiredFieldError = exports.InvalidInputError = exports.ValidationError = exports.MigrationError = exports.ConstraintViolationError = exports.ForeignKeyError = exports.DuplicateKeyError = exports.TransactionError = exports.QueryError = exports.ConnectionError = exports.EntityNotFoundError = exports.NotFoundError = exports.DatabaseError = exports.SBFError = exports.ErrorCodeHttpStatus = exports.ErrorCodeDescriptions = exports.ErrorCode = void 0;
exports.assertSBF = exports.wrapAsync = exports.createErrorHandler = exports.sanitizeErrorForExternal = exports.formatErrorForLogging = exports.isServerError = exports.isClientError = void 0;
var codes_1 = require("./codes");
Object.defineProperty(exports, "ErrorCode", { enumerable: true, get: function () { return codes_1.ErrorCode; } });
Object.defineProperty(exports, "ErrorCodeDescriptions", { enumerable: true, get: function () { return codes_1.ErrorCodeDescriptions; } });
Object.defineProperty(exports, "ErrorCodeHttpStatus", { enumerable: true, get: function () { return codes_1.ErrorCodeHttpStatus; } });
var base_1 = require("./base");
Object.defineProperty(exports, "SBFError", { enumerable: true, get: function () { return base_1.SBFError; } });
var database_1 = require("./database");
Object.defineProperty(exports, "DatabaseError", { enumerable: true, get: function () { return database_1.DatabaseError; } });
Object.defineProperty(exports, "NotFoundError", { enumerable: true, get: function () { return database_1.NotFoundError; } });
Object.defineProperty(exports, "EntityNotFoundError", { enumerable: true, get: function () { return database_1.EntityNotFoundError; } });
Object.defineProperty(exports, "ConnectionError", { enumerable: true, get: function () { return database_1.ConnectionError; } });
Object.defineProperty(exports, "QueryError", { enumerable: true, get: function () { return database_1.QueryError; } });
Object.defineProperty(exports, "TransactionError", { enumerable: true, get: function () { return database_1.TransactionError; } });
Object.defineProperty(exports, "DuplicateKeyError", { enumerable: true, get: function () { return database_1.DuplicateKeyError; } });
Object.defineProperty(exports, "ForeignKeyError", { enumerable: true, get: function () { return database_1.ForeignKeyError; } });
Object.defineProperty(exports, "ConstraintViolationError", { enumerable: true, get: function () { return database_1.ConstraintViolationError; } });
Object.defineProperty(exports, "MigrationError", { enumerable: true, get: function () { return database_1.MigrationError; } });
var validation_1 = require("./validation");
Object.defineProperty(exports, "ValidationError", { enumerable: true, get: function () { return validation_1.ValidationError; } });
Object.defineProperty(exports, "InvalidInputError", { enumerable: true, get: function () { return validation_1.InvalidInputError; } });
Object.defineProperty(exports, "MissingRequiredFieldError", { enumerable: true, get: function () { return validation_1.MissingRequiredFieldError; } });
Object.defineProperty(exports, "InvalidFormatError", { enumerable: true, get: function () { return validation_1.InvalidFormatError; } });
Object.defineProperty(exports, "OutOfRangeError", { enumerable: true, get: function () { return validation_1.OutOfRangeError; } });
Object.defineProperty(exports, "SchemaValidationError", { enumerable: true, get: function () { return validation_1.SchemaValidationError; } });
var external_1 = require("./external");
Object.defineProperty(exports, "ExternalServiceError", { enumerable: true, get: function () { return external_1.ExternalServiceError; } });
Object.defineProperty(exports, "AIProviderError", { enumerable: true, get: function () { return external_1.AIProviderError; } });
Object.defineProperty(exports, "RateLimitError", { enumerable: true, get: function () { return external_1.RateLimitError; } });
Object.defineProperty(exports, "TimeoutError", { enumerable: true, get: function () { return external_1.TimeoutError; } });
Object.defineProperty(exports, "NetworkError", { enumerable: true, get: function () { return external_1.NetworkError; } });
Object.defineProperty(exports, "APIError", { enumerable: true, get: function () { return external_1.APIError; } });
Object.defineProperty(exports, "ServiceUnavailableError", { enumerable: true, get: function () { return external_1.ServiceUnavailableError; } });
Object.defineProperty(exports, "QuotaExceededError", { enumerable: true, get: function () { return external_1.QuotaExceededError; } });
Object.defineProperty(exports, "InvalidResponseError", { enumerable: true, get: function () { return external_1.InvalidResponseError; } });
var content_1 = require("./content");
Object.defineProperty(exports, "ContentProcessingError", { enumerable: true, get: function () { return content_1.ContentProcessingError; } });
Object.defineProperty(exports, "EmbeddingError", { enumerable: true, get: function () { return content_1.EmbeddingError; } });
Object.defineProperty(exports, "IndexingError", { enumerable: true, get: function () { return content_1.IndexingError; } });
Object.defineProperty(exports, "ExtractionError", { enumerable: true, get: function () { return content_1.ExtractionError; } });
Object.defineProperty(exports, "ChunkingError", { enumerable: true, get: function () { return content_1.ChunkingError; } });
Object.defineProperty(exports, "VectorOperationError", { enumerable: true, get: function () { return content_1.VectorOperationError; } });
var transformation_1 = require("./transformation");
Object.defineProperty(exports, "TransformationError", { enumerable: true, get: function () { return transformation_1.TransformationError; } });
var podcast_1 = require("./podcast");
Object.defineProperty(exports, "PodcastError", { enumerable: true, get: function () { return podcast_1.PodcastError; } });
var domain_1 = require("./domain");
Object.defineProperty(exports, "DomainError", { enumerable: true, get: function () { return domain_1.DomainError; } });
Object.defineProperty(exports, "SensitivityViolationError", { enumerable: true, get: function () { return domain_1.SensitivityViolationError; } });
Object.defineProperty(exports, "LifecycleTransitionError", { enumerable: true, get: function () { return domain_1.LifecycleTransitionError; } });
Object.defineProperty(exports, "LifecycleExpiredError", { enumerable: true, get: function () { return domain_1.LifecycleExpiredError; } });
Object.defineProperty(exports, "RelationshipError", { enumerable: true, get: function () { return domain_1.RelationshipError; } });
Object.defineProperty(exports, "CircularDependencyError", { enumerable: true, get: function () { return domain_1.CircularDependencyError; } });
Object.defineProperty(exports, "TenantIsolationError", { enumerable: true, get: function () { return domain_1.TenantIsolationError; } });
Object.defineProperty(exports, "ChecksumMismatchError", { enumerable: true, get: function () { return domain_1.ChecksumMismatchError; } });
var serializer_1 = require("./serializer");
Object.defineProperty(exports, "serializeError", { enumerable: true, get: function () { return serializer_1.serializeError; } });
Object.defineProperty(exports, "toAPIErrorResponse", { enumerable: true, get: function () { return serializer_1.toAPIErrorResponse; } });
Object.defineProperty(exports, "toAPISuccessResponse", { enumerable: true, get: function () { return serializer_1.toAPISuccessResponse; } });
Object.defineProperty(exports, "getHttpStatusCode", { enumerable: true, get: function () { return serializer_1.getHttpStatusCode; } });
Object.defineProperty(exports, "isRetryableError", { enumerable: true, get: function () { return serializer_1.isRetryableError; } });
Object.defineProperty(exports, "isClientError", { enumerable: true, get: function () { return serializer_1.isClientError; } });
Object.defineProperty(exports, "isServerError", { enumerable: true, get: function () { return serializer_1.isServerError; } });
Object.defineProperty(exports, "formatErrorForLogging", { enumerable: true, get: function () { return serializer_1.formatErrorForLogging; } });
Object.defineProperty(exports, "sanitizeErrorForExternal", { enumerable: true, get: function () { return serializer_1.sanitizeErrorForExternal; } });
Object.defineProperty(exports, "createErrorHandler", { enumerable: true, get: function () { return serializer_1.createErrorHandler; } });
Object.defineProperty(exports, "wrapAsync", { enumerable: true, get: function () { return serializer_1.wrapAsync; } });
Object.defineProperty(exports, "assertSBF", { enumerable: true, get: function () { return serializer_1.assertSBF; } });
//# sourceMappingURL=index.js.map