// This file is auto-generated by scripts/generate-ontology.ts
// Do not edit manually

export type EntityType = 'person' | 'org' | 'team' | 'role' | 'topic' | 'policy' | 'standard' | 'risk' | 'control' | 'project' | 'process' | 'task' | 'service' | 'asset' | 'kpi' | 'objective' | 'meeting' | 'decision' | 'issue' | 'approval' | 'artifact' | 'dataset' | 'report' | 'document' | 'form' | 'account' | 'product' | 'order' | 'invoice' | 'contract' | 'payment' | 'shipment' | 'customer' | 'site' | 'facility' | 'equipment' | 'material' | 'batch' | 'inspection' | 'incident' | 'change' | 'release' | 'observation' | 'complaint' | 'visit' | 'ticket' | 'patient' | 'case' | 'diagnosis' | 'treatment' | 'labresult' | 'procedure' | 'specimen' | 'consent' | 'farm' | 'field' | 'crop' | 'input' | 'harvest' | 'weather' | 'sensor' | 'regulation' | 'clause' | 'casefile' | 'audit' | 'breach' | 'finding' | 'campaign' | 'adcreative' | 'transaction' | 'loyaltyprogram' | 'review' | 'configurationitem' | 'experiment' | 'hypothesis' | 'protocol' | 'sample' | 'metric' | 'result' | 'aeisession' | 'aiinsight' | 'automationrule' | 'overridelog';

export const ENTITY_TYPES: EntityType[] = [
  'person',
  'org',
  'team',
  'role',
  'topic',
  'policy',
  'standard',
  'risk',
  'control',
  'project',
  'process',
  'task',
  'service',
  'asset',
  'kpi',
  'objective',
  'meeting',
  'decision',
  'issue',
  'approval',
  'artifact',
  'dataset',
  'report',
  'document',
  'form',
  'account',
  'product',
  'order',
  'invoice',
  'contract',
  'payment',
  'shipment',
  'customer',
  'site',
  'facility',
  'equipment',
  'material',
  'batch',
  'inspection',
  'incident',
  'change',
  'release',
  'observation',
  'complaint',
  'visit',
  'ticket',
  'patient',
  'case',
  'diagnosis',
  'treatment',
  'labresult',
  'procedure',
  'specimen',
  'consent',
  'farm',
  'field',
  'crop',
  'input',
  'harvest',
  'weather',
  'sensor',
  'regulation',
  'clause',
  'casefile',
  'audit',
  'breach',
  'finding',
  'campaign',
  'adcreative',
  'transaction',
  'loyaltyprogram',
  'review',
  'configurationitem',
  'experiment',
  'hypothesis',
  'protocol',
  'sample',
  'metric',
  'result',
  'aeisession',
  'aiinsight',
  'automationrule',
  'overridelog'
];

export type RelationType = 'depends_on' | 'produces' | 'consumes' | 'causes' | 'results_in' | 'involves' | 'governs' | 'inspects' | 'inspected_by' | 'located_at' | 'complies_with' | 'reports_to' | 'manages' | 'author_of' | 'derived_from' | 'cites' | 'tests' | 'detects' | 'services' | 'monitors' | 'tracks' | 'sells_to' | 'purchases_from' | 'member_of' | 'resolves' | 'mitigates' | 'relates_to' | 'belongs_to' | 'targets' | 'bundles' | 'duplicates' | 'child_of' | 'parent_of';

export const RELATION_TYPES: RelationType[] = [
  'depends_on',
  'produces',
  'consumes',
  'causes',
  'results_in',
  'involves',
  'governs',
  'inspects',
  'inspected_by',
  'located_at',
  'complies_with',
  'reports_to',
  'manages',
  'author_of',
  'derived_from',
  'cites',
  'tests',
  'detects',
  'services',
  'monitors',
  'tracks',
  'sells_to',
  'purchases_from',
  'member_of',
  'resolves',
  'mitigates',
  'relates_to',
  'belongs_to',
  'targets',
  'bundles',
  'duplicates',
  'child_of',
  'parent_of'
];

export interface CoreEntityParameters {
  'uid'?: any;
  'type'?: any;
  'title'?: any;
  'aliases'?: any;
  'description'?: any;
  'created'?: any;
  'updated'?: any;
  'status'?: any;
  'owner'?: any;
  'stakeholders'?: any;
  'tags'?: any;
  'importance'?: any;
  'confidence'?: any;
  'lifecycle.state'?: any;
  'lifecycle.review_at'?: any;
  'lifecycle.dissolve_at'?: any;
  'sensitivity.level'?: any;
  'sensitivity.pii'?: any;
  'privacy.permissions.cloud_ai'?: any;
  'privacy.permissions.local_ai'?: any;
  'privacy.permissions.export'?: any;
  'location.site'?: any;
  'location.region'?: any;
  'location.gps'?: any;
  'relations'?: any;
  'provenance.sources'?: any;
  'attachments'?: any;
  'metrics'?: any;
  'audit.changes'?: any;
  'audit.approvals'?: any;
  'audit.override.human_last'?: any;
  'tool.compat.obsidian'?: any;
  'tool.compat.notebooklm'?: any;
  'tool.compat.anythingllm'?: any;
}

export interface AIParameters {
  'ai.insights'?: any;
  'ai.pattern_score'?: any;
  'ai.embedding'?: any;
  'human.validation.confirmed'?: any;
  'explainability'?: any;
}

export interface DomainParameters {
  manufacturing_supply_chain?: {
    'batch_id'?: any;
    'lot_no'?: any;
    'material_code'?: any;
    'supplier'?: any;
    'quality_grade'?: any;
    'inspection_result'?: any;
    'shipment_id'?: any;
    'temperature'?: any;
    'humidity'?: any;
    'weight'?: any;
    'unit_cost'?: any;
  };
  healthcare_veterinary?: {
    'patient_id'?: any;
    'dob'?: any;
    'species'?: any;
    'diagnosis_code'?: any;
    'treatment_plan'?: any;
    'procedure_code'?: any;
    'specimen_id'?: any;
    'lab_test'?: any;
    'consent_ref'?: any;
    'privacy_tier'?: any;
  };
  itil_devops?: {
    'service_id'?: any;
    'ci_type'?: any;
    'severity'?: any;
    'priority'?: any;
    'ticket_status'?: any;
    'mttr'?: any;
    'sla_target'?: any;
    'deployment_id'?: any;
    'automation_rule_id'?: any;
  };
  legal_risk_compliance?: {
    'case_id'?: any;
    'regulation_ref'?: any;
    'clause'?: any;
    'control_id'?: any;
    'risk_level'?: any;
    'likelihood'?: any;
    'impact'?: any;
    'evidence_ref'?: any;
    'audit_date'?: any;
    'breach_status'?: any;
  };
  construction_engineering?: {
    'project_code'?: any;
    'permit_no'?: any;
    'phase'?: any;
    'milestone'?: any;
    'budget'?: any;
    'subcontractor'?: any;
    'material_type'?: any;
    'safety_score'?: any;
    'inspection_id'?: any;
  };
  retail_ecommerce_advertising?: {
    'sku'?: any;
    'campaign_id'?: any;
    'ad_channel'?: any;
    'ctr'?: any;
    'conversion_rate'?: any;
    'order_no'?: any;
    'customer_id'?: any;
    'payment_status'?: any;
    'region'?: any;
    'return_rate'?: any;
  };
  agriculture_food_systems?: {
    'farm_id'?: any;
    'field_no'?: any;
    'crop_type'?: any;
    'input_type'?: any;
    'harvest_date'?: any;
    'yield_kg'?: any;
    'moisture_pct'?: any;
    'soil_pH'?: any;
    'weather_condition'?: any;
    'sensor_id'?: any;
  };
}