import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, '..');
const ONTOLOGY_PATH = path.join(ROOT_DIR, 'vault', '00_Meta', 'ontology.yaml');
const OUTPUT_PATH = path.join(ROOT_DIR, 'packages', 'types', 'src', 'generated-ontology.ts');

interface Ontology {
  entities: string[];
  relations: string[];
  core_parameters: string[];
  domain_parameters: Record<string, string[]>;
  ai_parameters: string[];
}

function generateCode(ontology: Ontology): string {
  const entityTypes = ontology.entities.map(e => `'${e}'`).join(' | ');
  const relationTypes = ontology.relations.map(r => `'${r}'`).join(' | ');

  const lines = [
    '// This file is auto-generated by scripts/generate-ontology.ts',
    '// Do not edit manually',
    '',
    `export type EntityType = ${entityTypes};`,
    '',
    `export const ENTITY_TYPES: EntityType[] = [`,
    ontology.entities.map(e => `  '${e}'`).join(',\n'),
    '];',
    '',
    `export type RelationType = ${relationTypes};`,
    '',
    `export const RELATION_TYPES: RelationType[] = [`,
    ontology.relations.map(r => `  '${r}'`).join(',\n'),
    '];',
    '',
    'export interface CoreEntityParameters {',
    ...ontology.core_parameters.map(p => `  '${p}'?: any;`),
    '}',
    '',
    'export interface AIParameters {',
    ...ontology.ai_parameters.map(p => `  '${p}'?: any;`),
    '}',
    '',
    'export interface DomainParameters {',
  ];

  for (const [domain, params] of Object.entries(ontology.domain_parameters)) {
    lines.push(`  ${domain}?: {`);
    lines.push(...params.map(p => `    '${p}'?: any;`));
    lines.push('  };');
  }
  lines.push('}');

  return lines.join('\n');
}

try {
  const fileContent = fs.readFileSync(ONTOLOGY_PATH, 'utf8');
  const ontology = yaml.load(fileContent) as Ontology;
  const code = generateCode(ontology);
  fs.writeFileSync(OUTPUT_PATH, code);
  console.log(`Successfully generated ontology types at ${OUTPUT_PATH}`);
} catch (error) {
  console.error('Error generating ontology:', error);
  process.exit(1);
}
